// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdwENoKZJTnnp3fPlX1Jyq2GPD61pYKyU',
    appId: '1:762114510476:web:14cd6de07a902f5fafb5a9',
    messagingSenderId: '762114510476',
    projectId: 'expense-tracker-e528f',
    authDomain: 'expense-tracker-e528f.firebaseapp.com',
    storageBucket: 'expense-tracker-e528f.firebasestorage.app',
    measurementId: 'G-L1DZ383649',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAaqzv7fB8tThFVudOD5TRcsgOnMfvizs',
    appId: '1:762114510476:android:5bf68998b124ffaaafb5a9',
    messagingSenderId: '762114510476',
    projectId: 'expense-tracker-e528f',
    storageBucket: 'expense-tracker-e528f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApQUQZl8xvRbi7ktNZdV4RzTH9AnFDqSM',
    appId: '1:762114510476:ios:552f4b367ff72244afb5a9',
    messagingSenderId: '762114510476',
    projectId: 'expense-tracker-e528f',
    storageBucket: 'expense-tracker-e528f.firebasestorage.app',
    androidClientId: '762114510476-7sja14gnsv4himsqkpp3dogqtrk8u3ds.apps.googleusercontent.com',
    iosClientId: '762114510476-8apqhs031tcra0tf4q90mh3b15juv05l.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApQUQZl8xvRbi7ktNZdV4RzTH9AnFDqSM',
    appId: '1:762114510476:ios:552f4b367ff72244afb5a9',
    messagingSenderId: '762114510476',
    projectId: 'expense-tracker-e528f',
    storageBucket: 'expense-tracker-e528f.firebasestorage.app',
    androidClientId: '762114510476-7sja14gnsv4himsqkpp3dogqtrk8u3ds.apps.googleusercontent.com',
    iosClientId: '762114510476-8apqhs031tcra0tf4q90mh3b15juv05l.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdwENoKZJTnnp3fPlX1Jyq2GPD61pYKyU',
    appId: '1:762114510476:web:c14cd7283f08e47fafb5a9',
    messagingSenderId: '762114510476',
    projectId: 'expense-tracker-e528f',
    authDomain: 'expense-tracker-e528f.firebaseapp.com',
    storageBucket: 'expense-tracker-e528f.firebasestorage.app',
    measurementId: 'G-ES7YNCBY30',
  );

}